### ISSUE TITLE
wulf7/libinotify-kqueue integration

### ISSUE THREAD

**Issue by wulf7** [dmatveev/libinotify-kqueue#19]
Hi, Dmitry
I had almost completed refactoring of my work and placed it into integrate-dmatveev branch of wulf7/libinotify-kqueue repo
All changes can be combined into following parts:
5eae094 -  2e370b2 move barriers code to compat.c
b3e9304 -  147e07d remove some watch deletion optimizations for code simplification
a40e2f7 -  6c30885 Combine single and bulk write code paths using writev scatter-gather operations
632734b -  dab864e Replace linked list implementation with BSD queue(3) macroses and make some directory diff optimizations
182cfa0 - 497b349 Switch to POSIX.1-2008 relative pathname functions for file operations.
ae82cd9 - f1624ee open() flags improvements
8e1afe4 - 09aca85 Make most of internal processing inotify-watch centric. E.g. split worker_sets on per inotify_watch basis
228e972 - 3f70da7 Use inode numbers instead filenames for processing of kqueue watches (like kernel does)
6e28faf - bfb6346 Replace worker-set arrays with more flexible RB-tree based structures
5204da0 - 32da88e Implement most of inotify_add_or_modify flags
e4d0d92 - 99aeec4 Some fixes and optimizations of kqueue watch creation
4e4707a - a242780 Miscellaneous small fixes
3f71d2e - 3ee44d5 Implementation of events which require kernel patching (IN_OPEN, IN_CLOSE, IN_ACCESS)
340089c - ... etc

Resulting code is not extensively tested but is able to pass test suite under valgrind control with jemalloc memory debugging features enabled.

**Comment by dmatveev** [comment]
Perfect, Vladimir! I will do my best to merge it on this holidays.

**Comment by wulf7** [comment]
All changes have been merged

**Comment by dmatveev** [comment]
Thanks again for your great work!
