### ISSUE TITLE
[suggestion] Implement command line interface like 'inotifywait' in linux

### ISSUE THREAD

**Issue by yurivict** [dmatveev/libinotify-kqueue#28]
Currently there is no way to wait for file deletion event (for example) in the shell program. So 'inotifywait' would be very useful, and should also be very easy to add having the library ready. Also here is the most natural place for it. Your project will become so much more useful.

**Comment by xaionaro** [comment]
I'm just an user of libinotify-kqueue, but I think you should just ask the author of [inotify-tools](https://github.com/rvoicilas/inotify-tools) to port it to *BSD using this library.

Also [clsync](https://github.com/xaionaro/clsync) is ported to FreeBSD. It's not an analog of inotifywait, but may be used in similar purposes. For example:

    printf "+fsomefile\n+w^$\n-*\n" > /tmp/rules | clsync -Secho -Msimple -t0 -w0 -T0 -W /mnt/somedir/ -R /tmp/rules

**Comment by yurivict** [comment]
Thanks @xaionaro , I was able to build inotify-tools as a FreeBSD port with the minimal effort. Will submit this port.

**Comment by dmatveev** [comment]
I assume that the "inotifywait" you mention here can be easily ported using the library. It is the goal of the project :)

**Comment by yurivict** [comment]
This is already done, thanks.
