### ISSUE TITLE
#include <sys/tree.h> is missing on FreeBSD

### ISSUE THREAD

**Issue by yurivict** [dmatveev/libinotify-kqueue#30]

**Comment by wulf7** [comment]
Which version of FreeBSD are you usings? sys/tree.h has been imported into source tree in 2002

Anyway I have created a pull request #31 with bundled sys/tree.h so you can try that code now

**Comment by yurivict** [comment]
10.1
The file tree.h isn't missing, include is missing. I added this to quick-fix thebuild:
````
@echo "#include <sys/tree.h>" >> ${WRKSRC}/config.h
````

**Comment by wulf7** [comment]
Are you trying to compile libinotify out of FreeBSD port system through hacking of port`s Makefile? If so it would be a wrong way. You should run full autotools suite than configure than resulting Makefile rather than just run ports bundled Makefile

**Comment by yurivict** [comment]
Free port already bypasses autotools. I was updating it to the latest version, and found that this include is missing. It was added for some other OSes, but not FreeBSD in code.

**Comment by wulf7** [comment]
The code evolved since port version. It now requires autotools

**Comment by wulf7** [comment]
Run autogen.sh && configure && make in ${WRKSRC} directory and dont run make on port bundled Makefile

**Comment by yurivict** [comment]
Port doesn't use autogen.sh the way how it is defined. autogen.sh would require perl, and will take literally 20 times longer to build. So it avoids this. In any case, there is no action required. Thanks.

**Comment by dmatveev** [comment]
Thanks, Vladimir, for help with this issue!
