### ISSUE TITLE
Question: Only watch directories

### ISSUE THREAD

**Issue by ejurgensen** [dmatveev/libinotify-kqueue#36]
I maintain [forked-daapd](https://github.com/ejurgensen/forked-daapd) which uses inotify for Linux and kqueue for FreeBSD to watch the users music library. For FreeBSD, I would like to switch to libinotify-kqueue, since that would make maintenance much easier. However, music libraries can be quite large, so I can't let libinotify-kqueue watch every file, since that will lead to too many open files.

To get around this, the current kqueue solution in forked-daapd only opens/watches directories. So I was wondering if there is some way to make libinotify also only open directories?

**Comment by wulf7** [comment]
If you would not specify IN_ATTRIB IN_ACCESS IN_OPEN IN_CLOSE or IN_MODIFY flags than libinotify would not open all files and directories inside watched dir. Take a closer look at inotify_to_kqueue function in watch.c It shows you inotify -> kqueue flags conversion. Libinotify does not open file or directory when resulting kqueue flags set is empty

**Comment by ejurgensen** [comment]
Err, but I *do* want to watch (and open) directories, just want to avoid files. Currently, the application does (for each directory in the library):

```
wd = open(dir_path, O_RDONLY | O_NONBLOCK);
EV_SET(&kev, wd, EVFILT_VNODE, EV_ADD | EV_CLEAR, NOTE_DELETE | NOTE_WRITE | NOTE_RENAME, 0, NULL);

```

So I think I especially would need a NOTE_WRITE on each dir, but also DELETE and RENAME. From looking at the code it doesn't seem possible to do that? Or maybe I misunderstood what you meant?

**Comment by wulf7** [comment]
Libinotify does not analyse NOTE_DELETE or NOTE_RENAME events in subdirectories. It only analyses NOTE_WRITE event on parent directory and than does rereading and diffing of it content to get a list of renamed, deleted or created files.

**Comment by ejurgensen** [comment]
Ah ok, I suppose NOTE_WRITE will be enough then. So if I do inotify_add_watch(fd, dir_path, 0) I will get a NOTE_WRITE on just the dir?

**Comment by wulf7** [comment]
you should do something like inotify_add_watch(fd, dir_path, IN_CREATE | IN_DELETE | IN_MOVE) to get a NOTE_WRITE on "dir_path"

**Comment by ejurgensen** [comment]
Thanks a million, this is exactly what I needed! I’ve tested it a bit, and it seems to work very well. Now I can switch to libinotify for FreeBSD, which should make the FreeBSD implementation much simpler and easier to maintain. :-)
