### ISSUE TITLE
"make test" sometimes gets killed with SIGPIPE

### ISSUE THREAD

**Issue by dmatveev** [dmatveev/libinotify-kqueue#8]
A rare but quite reproducible issue (at least) on NetBSD 6.99.

**Comment by dmatveev** [comment]
Still reproducible on today's HEAD (74a82f5)

**Comment by wulf7** [comment]
I hope 2443ba0 in wulf7/libinotify-kqueue fixed this issue

**Comment by dmatveev** [comment]
Closing as no longer relevant & all gone to https://github.com/libinotify-kqueue/libinotify-kqueue
